name: Delete Azure Container App

on:
  workflow_dispatch:
    inputs:
      container_url_or_name:
        description: 'Container App URL or Name'
        required: true
        type: string
      resource_group:
        description: 'Azure Resource Group'
        required: true
        type: string
      subscription_id:
        description: 'Azure Subscription ID'
        required: true
        type: string

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          subscription-id: ${{ github.event.inputs.subscription_id }}

      - name: Extract Container App Name
        id: extract
        run: |
          if [[ "${{ github.event.inputs.container_url_or_name }}" == http* ]]; then
            CONTAINER_APP_NAME=$(echo "${{ github.event.inputs.container_url_or_name }}" | sed -E 's~https?://([^.]+)\..*~\1~')
          else
            CONTAINER_APP_NAME="${{ github.event.inputs.container_url_or_name }}"
          fi
          echo "CONTAINER_APP_NAME=$CONTAINER_APP_NAME" >> $GITHUB_ENV

      - name: Delete Container App
        id: deleteapp
        run: |
          set +e
          az containerapp delete --name "$CONTAINER_APP_NAME" --resource-group "${{ github.event.inputs.resource_group }}" --yes > delete_log.txt 2>&1
          STATUS=$?
          echo "status=$STATUS" >> $GITHUB_OUTPUT
          if [ $STATUS -eq 0 ]; then
            echo "success" > result.txt
          else
            echo "failure" > result.txt
            cat delete_log.txt
          fi

      - name: Upload Result Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: delete-result-${{ env.CONTAINER_APP_NAME }}
          path: result.txt

      - name: Upload Log Artifact (optional)
        uses: actions/upload-artifact@v4.6.2
        with:
          name: delete-log-${{ env.CONTAINER_APP_NAME }}
          path: delete_log.txt
